#ifndef _IOCTL_GLOBALS_H_
#define _IOCTL_GLOBALS_H_

#include <SubAuth.h>

#define IO_HIDE_PROC        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2890, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_PID_PROC         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2891, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_LOCK_PROC        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2892, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_LOCK_KEY         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2893, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif